### ISSUE TITLE
Failed to load the duplicate-line-or-selection package

### ISSUE THREAD

**Issue by seelts** [nick/duplicate-line-or-selection#9]
1. Install duplicate-line-or-selection plugin (v0.8.0)
2. Get this error

There is no (discoverable) 'ctrl-shift-D' keybinding in Atom

**Atom Version**: 1.12.1
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [duplicate-line-or-selection](https://github.com/nick/duplicate-line-or-selection) package, v0.8.0

### Stack Trace

Failed to load the duplicate-line-or-selection package

```
At Duplicate key 'ctrl-shift-D'

Error: Duplicate key 'ctrl-shift-D'
  at Object.detectDuplicateKeys (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:268:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:387:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:384:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:110:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:466:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:410:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:763:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "closeEmptyWindows": false,
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited",
    "useCustomTitleBar": true,
    "warnOnLargeFileLimit": 0.5
  }
}
```

### Installed Packages

```coffee
# User
duplicate-line-or-selection, v0.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by yaneony** [comment]
I think that happens because "duplicate line" is now implemented within a atom itself.

**Comment by seelts** [comment]
@jsieler but the error is about key binding... How can it be duplicating — there is no such binding in Atom.

**Comment by yaneony** [comment]
Looks like there is:

Keystroke           Command             Source    Selector
ctrl-shift-D    editor:duplicate-lines      Core      atom-workspace atom-text-editor:not([mini])

As you can see, source is "CORE".

**Comment by seelts** [comment]
Where did you find this line?
And what should I do to make plugin works?

**Comment by yaneony** [comment]
Look inside "keybindings" in Atom. Search for "ctrl-shift-D". I think to make it work you need to remove your keybinding.

**Comment by seelts** [comment]
That was the first thing I've done.
As I've wrote in issue description, I have no such binding in my Atom instance.

**Comment by seelts** [comment]
I've added these lines to my keybindings:

```
'atom-workspace atom-text-editor:not([mini])':
  'shift-cmd-D': 'unset!'
  'ctrl-shift-D': 'unset!'
```

As I'm on mac, I have cmd-shift-d for native Atom duplicating.
Nothing has changed.
The same error.

**Comment by cengizhan** [comment]
even disabling keybindig in this package doesn't do anything. the conflict can not be resolved. atom still gives error at startup

**Comment by nicothin** [comment]
and I have such an error

**Comment by nicothin** [comment]
I added a file `keymap.cson`

```
'atom-workspace atom-text-editor:not([mini])':
    'ctrl-shift-D': 'duplicate-line-or-selection:duplicate'
```

and plugin work, but I still see the error on Atom start

**Comment by yaneony** [comment]
Is it dead? Please merge commit.

**Comment by nick** [comment]
Merged. Hope this fixes it

**Comment by seelts** [comment]
Works! Great, thanks a lot!
